### ISSUE TITLE
add-on installs

### ISSUE THREAD

**Issue by ClaytonOlleyITN** [aws-quickstart/quickstart-splunk-enterprise#15]
I can't seem to find direct download links (in .spl format?) for installing add-ons via the CF template. What am I missing?

**Comment by rarsan** [comment]
Hi @ClaytonOlleyITN ,  provided by user . The user is expected to host these apps/add-ons in a private S3 bucket or any file server and provide these download links. The deployment will then pre-install apps/add-ons from the URLs specified as comma-separated list in template parameters `SearchHeadApps` and `IndexerApps`.For more information on how to package custom apps into .spl format, please refer to http://dev.splunk.com/view/SP-CAAAEMY#package
