### ISSUE TITLE
Using Private IP Addresses causes CF to timeout

### ISSUE THREAD

**Issue by cedman1** [aws-quickstart/quickstart-splunk-enterprise#17]
I am attempting to setup the environment without using (associating Public IP Addresses to the servers) and the cloud formation never completes.  The lack of Public IP Addresses is a requirement within the private AWS environment.  I am editing the associatepublicIP value from true to false.

Is it possible to use this cf with only private IP addresses/ no public IP addresses?

**Comment by sshvans** [comment]
@cedman1 This Quick Start requires instances to be in public subnet.
