### ISSUE TITLE
AWS app installation failed

### ISSUE THREAD

**Issue by anilaws** [aws-quickstart/quickstart-splunk-enterprise#18]
i am trying to install AWS app, AWS add on and Python for Scientific Computing (for Linux 64-bit) providing cloudformation template parameter SearchHeadApps as 
https://splunkbase.splunk.com/app/2882/,https://splunkbase.splunk.com/app/1274/,https://splunkbase.splunk.com/app/1876/ and when i check the logs i get the error as
Downloading app https://splunkbase.splunk.com/app/1876/
--2018-02-12 19:00:41--  https://splunkbase.splunk.com/app/1876/
Resolving splunkbase.splunk.com (splunkbase.splunk.com)... 54.148.88.225, 35.161.95.55, 52.41.48.242
Connecting to splunkbase.splunk.com (splunkbase.splunk.com)|54.148.88.225|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘/tmp/app2.spl’

/tmp/app2.spl                    [ <=>                                          ]  87.23K  --.-KB/s    in 0.002s  

2018-02-12 19:00:41 (41.2 MB/s) - ‘/tmp/app2.spl’ saved [89328]

Installing app...

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Extracting tarball failed

**Comment by billbartlett** [comment]
Hi Anil,

You'll need to download the spl files and host them somewhere for the template to download -- most commonly an s3 bucket.  The URLs that you've chosen are direct links to the applications, and that is the cause of your errors.   

Does that make sense?

Thanks,
Bill

**Comment by anilaws** [comment]
could you please provide me the link to documentation i can refer?

**Comment by billbartlett** [comment]
The documentation says "Comma-separated list of URLs for the Splunk app (or add-on)
tarballs (.spl files) to pre-install on indexer(s)."  It's just like it sounds - the code will issue a wget on the URLs provided, unzip them, and place them in the apps folder of the Splunk installation. You can host them on your own webserver if you have one, or on an S3 bucket with a world-readable flag on the objects that you want to download.  Then simply enter the URLs for each app that you want to install, separated via commas.  

Thanks,
Bill
