### ISSUE TITLE
autoLB invalid Key

### ISSUE THREAD

**Issue by kddejong** [aws-quickstart/quickstart-splunk-enterprise#25]
I'm seeing this error on a Splunk restart.  I don't believe this option exists with newer versions of Splunk

`Invalid key in stanza [tcpout:indexer_cluster_peers] in /opt/splunk/etc/apps/base-autogenerated/local/outputs.conf, line 11: autoLB  (value:  true).`

**Comment by sshvans** [comment]
@kddejong Thanks for reporting the issue. I'll take a look into it and get back to you.

**Comment by billbartlett** [comment]
@kddejong The autolb setting has now been locked to 'true' and has been noted in the online Splunk documentation: http://docs.splunk.com/Documentation/Splunk/7.1.2/Installation/AboutupgradingREADTHISFIRST  

The error you see should be a warning and not a critical blocker.  Is that the case for you?  We will be updating this QuickStart to address this, along with a few other bugs.

**Comment by sshvans** [comment]
This issue has been fixed.
