### ISSUE TITLE
Broken with 7.1

### ISSUE THREAD

**Issue by mikegchambers** [aws-quickstart/quickstart-splunk-enterprise#26]
**After much messing around I have come to the conclusion that this QuickStart is broken for 7.1.** 

There are a number of issues which I started to fix, but my knowledge of Splunk is not good enough to offer pull request.  

In summary the userdata scripts do not work with 7.1.  If you are suffering the same issue, I would suggest running the March 2018 version of this script, or rolling your own.

Anyone wanting to carry on from where I left off....

**/templates/splunk-enterprise.template**  Line 744 (and all others like it) are missing an escape char on the <new line>, should read this:  (Although the issue does not seem to break anything)
```
"printf '%s\t%s\\n' \"$LOCALIP\" 'splunksearch' >> /etc/hosts\n",`
```

AND in the same file, to avoid the 'there is no admin user' issue, the following lines can be added  after line 746 (and all other locations like it): (This will enable you to log in to your servers)
```
"printf '[user_info]\\nPASSWORD = changeme\\n' > $SPLUNK_HOME/etc/system/local/user-seed.conf\n"
"service splunk restart\n"
```

However, even after making these changes, while you can no log in, to the best of my knowledge, the clusters fail, and its far from working.

Good luck.

**Comment by sshvans** [comment]
@mikegchambers Thanks for reporting the issue. I'll take a look into it and get back to you.

**Comment by AndyHuang1991** [comment]
also can't access splunk web with config password. So I roll back to March 2018's template and it works.

But in splunk web login page, it shows license expired. Is it  because 60 day trial license is based on commit time of this script? i.e. if I use 2018 March version, it will expired at June?

Anyone can help me? Thanks a lot :)

**Comment by mikegchambers** [comment]
@AndyHuang1991 the first fix I outlined in my OP enables you to login with the password you set.  If you know your way around Splunk there are other things you will need to fix from there on.  

FWIW: I had no issues with licenses uploaded via S3. 

The problem with the March 2018 template (as you probably know) is that it references v7.0.0.

**Comment by mikegchambers** [comment]
From further investigation I have suspicion that this bug is mostly related to changes in the AMI.  

I am using ami-9808acfa (ap-southeast-2) which has a Splunk guid set by default which gets in the way when trying to build clusters (nodes can't join clusters when the master has the same guid).  Its also has an AWS style local IP hostname set which gets confusing.  

I have created a fork with a fix, its not PR worthy but it works:
https://github.com/mikegchambers/quickstart-splunk-enterprise

**Comment by sshvans** [comment]
@mikegchambers @AndyHuang1991 These issues have been fixed.
