### ISSUE TITLE
QuickStart failing when creating a the resource 'SplunkSHCMember3'

### ISSUE THREAD

**Issue by deepakr6** [aws-quickstart/quickstart-splunk-enterprise#29]
Hello QS Team, 

The EC2 resource '**SplunkSHCMember3**' fails creation which eventually causes the entire stack to fail on creation. On reviewing system logs for the instance **SplunkSHCMember3** it looks like last command in user-data execution, which I'm guessing is responsible to setting captaincy for the search head returns a 'non-zero' exit code. 

Specific command: 

`sudo -u $SPLUNK_USER $SPLUNK_BIN bootstrap shcluster-captain -servers_list "https://10.0.1.38:8089,https://10.0.2.109:8089,https://$LOCALIP:8089" -auth admin:<password>`

This causes cfn-signal to send a failure signal to the CloudFormation stack. Can you please replicate this issue and suggest if there something I can do to fix it ?

**Comment by billbartlett** [comment]
Would you be able to try manually running that command on SHCMember3 and letting us know if it works as expected?

**Comment by nihe** [comment]
Hello @billbartlett @deepakr6 

I have the same issue.

**Comment by sshvans** [comment]
@deepakr6 @nihe This is fixed now.
