### ISSUE TITLE
Splunk CFN fails if the disk volume is set higher that 14000 GB

### ISSUE THREAD

**Issue by prats84** [aws-quickstart/quickstart-splunk-enterprise#7]
The stack fails likely due to disk volume issue using the CFN template. The first instance provisioned by the template is Splunk cluster-master, however, if the disk size specified is 14000GB and above the stack creations fails with error: 	'Failed to receive 1 resource signal(s) within the specified duration'

This would likely be due to the IOPS allocation taking a bit longer to format and mount the volume which would be causing the cfn-signal to timeout and thus initiating roll-back of the Stack.

**Comment by rarsan** [comment]
Thx for reporting this @prats84 . We're currently looking at this issue.
Are you deploying in a new or existing VPC?

**Comment by prats84** [comment]
Existing VPC.

**Comment by rarsan** [comment]
This can be closed. cc @sshvans.
